### ISSUE TITLE
Query error on Transactions

### ISSUE THREAD

**Issue by Pyrobolser** [adjoint-io/uplink-sdk-python#21]
Hello,

I have an Uplink network and I am using the Python SDK to interact with it. Everything is working fine but I cannot figure out how to use the **txhash** returned by **uplink_call_contract** to find the actual transaction and its content on Uplink.

Is there a way to do that?

I tried to query for transaction with:
```python
uplink.query("QUERY transactions WHERE txtype='CallContract';")
```
Or even just:
```python
uplink.query("QUERY transactions WHERE txtype='Call';")
```

But I get a SelectParse error every time. The query works correctly with the filter on origin for example so I don't really know how to diagnose this more. I don't really know if there is a way to query directly with the txhash that I am getting back from the method.

Thanks for your help

**Comment by tdietert** [comment]
First, try changing `txtype` to `tx_type`, and if you are trying to query by hash, use `hash =` instead of `txhash`.

**Comment by tdietert** [comment]
Also, `Call` is the correct `tx_type`. So, your query should be: 
```
uplink.query("QUERY transactions WHERE tx_type='Call';")
```

**Comment by Pyrobolser** [comment]
Awesome thanks!  

I can't update the documentation but in Querying this table was my issue:


Field | Type
-- | --
txtype | Text
origin | Address
timestamp | Int (POSIX time)

**Comment by tdietert** [comment]
yes, sorry! the documentation is a bit stale... although that part shouldn't be, it looks like just a typo from many months ago!

**Comment by Pyrobolser** [comment]
I'd be great to see hash on there too!

**Comment by tdietert** [comment]
In addition to that, we should be listing all the types of transactions that can be queried.
