### ISSUE TITLE
Inconsistent FCL value between Python and Java SDKs

### ISSUE THREAD

**Issue by moodmosaic** [adjoint-io/uplink-sdk-python#3]
It looks like the values types in the Python SDK as shown [here](https://github.com/adjoint-io/uplink-sdk-python/blob/10862ec53eddaa1aa74a2f63586623b8954d715c/uplink/enum.py#L17-L32) are a bit different from [those in the Java SDK](https://github.com/adjoint-io/uplink-sdk-java/blob/c7c06e65bb05dfb0287362a68e7744da46f22291/src/main/java/adjoint/uplink_sdk/client/FCLEnum.java#L23-L34):

```haskell
-- Java
...
VACCOUNT(5, "VAccount", "account")
VSTATE(12, "VState","state")
...

-- Python
...
VTypeAccount = 6
VTypeState = 14
...
```

Perhaps, only the label matters? 😕

**Comment by tdietert** [comment]
No, you are correct in your observation: The Java SDK value enumerations were outdated. Thanks :+1:

**Comment by sdiehl** [comment]
This should be fixed in https://github.com/adjoint-io/uplink-sdk-java/commit/0c114ca3d4698ee114199c78dc09adf81ef33f87.
