### ISSUE TITLE
'str' object has no attribute 'to_binary'

### ISSUE THREAD

**Issue by dhruvrana72** [adjoint-io/uplink-sdk-python#4]
I am getting the error mentioned in tile while calling contract.
I used the same private key which is used to create contract, account.
I used the following command to call create contract.
```
rpc.uplink_call_contract(private_key=sk, from_address=acct.address,
                                      contract_addr=contract.address,
                                      method='put', args=[("Hello")])
```
the script used to create the contract is this:

```
script= """global sig signature;
global bool isSet = False;

transition initial -> get;
transition put -> get;
transition get -> terminal;

@initial
put(msg x) {
  if ( !isSet ) {
      isSet = True;
      signature = sign(x);
      transitionTo(:get);
  } else { 
    return void;
  };
}

@get
isSigAvail() {
  return isSet;
}

@get
get() {
  if (isSet) {
    return signature;
  } else {
    terminate("This is the end.");
  };
}"""
```

here's the full error:

```
2                                       contract_addr=contract.address,
----> 3                                       method='put', args=[("Hello")])

/home/bhatia/Desktop/uplink-sdk-python/uplink/client.pyc in uplink_call_contract(self, private_key, from_address, contract_addr, method, args)
    357         txb = TxContract(Call(hdr))
    358 
--> 359         r, s = hdr.sign(private_key)
    360         signature = pack_signature(r, s)
    361 

/home/bhatia/Desktop/uplink-sdk-python/uplink/protocol.pyc in sign(self, privkey, k)
     59 
     60     def sign(self, privkey, k=None):
---> 61         stream = self.to_binary()
     62         return ecdsa_sign(privkey, stream, k=k)
     63 

/home/bhatia/Desktop/uplink-sdk-python/uplink/protocol.pyc in to_binary(self)
    619 
    620     def to_binary(self):
--> 621         binary_args = ''.join([arg.to_binary() for arg in self.args])
    622 
    623         structured = struct.pack(

AttributeError: 'str' object has no attribute 'to_binary'



```

Am I doing something wrong ?
Please help.

**Comment by faineance** [comment]
Calling methods on contracts involves wrapping the values in objects so we know to serialize them correctly, eg. `args=[VMsg("hello")]`

**Comment by faineance** [comment]
Does the same thing happen when using the https://github.com/adjoint-io/uplink-sdk-python/releases/tag/1.0 revision of the sdk?

If you are using pip to manage your dependencies this can be installed like so:
```
$ pip install git+https://github.com/adjoint-io/uplink-sdk-python.git@1.0
```
or by putting ` git+https://github.com/adjoint-io/uplink-sdk-python.git@1.0` in your `requirements.txt`

**Comment by dhruvrana72** [comment]
when I tried using 1.0 sdk version alot of things were not working.
I raised the issue here: https://github.com/adjoint-io/uplink-explorer/issues/69

Then, I was advised to use  this sdk version adjoint-io/uplink-sdk-python@a74b762

so, I am using an old sdk version for which everything works except call contract right now .

**Comment by dhruvrana72** [comment]
I checked in both the version that particular function is same in the 1.0 and 0.1 commit. So, I guess it will not make any difference after changing the version.

**Comment by dtseng123** [comment]
It was a bug regarding VMsg binary serialization which was fixed post-release. We will be releasing a new version at end of month, which contain a fix for this particular issue.

**Comment by sdiehl** [comment]
The latest version of our ledger has been shipped which completes the `Call` transaction serialization and exposes this machinery to the SDKs.

https://github.com/adjoint-io/uplink/releases/tag/1.1

**Comment by dhruvrana72** [comment]
Yes, This is fixed now.

Thank You.
